#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=96
boot() {
	is_base=`cat /tmp/orbi_type`
	if [ "x$is_base" = "xBase" ]; then
		echo "control-firmware will be Running once an hour at random time !!!" > /dev/console
		/usr/sbin/boot-notification &
	fi
}
